### ISSUE TITLE
Causing graphical issue when in editor (VAB or SPH)

### ISSUE THREAD

**Issue by M0khin** [KSP-RO/KSCSwitcher#13] opened 2021-07-03 11:22 UTC
Did report a minor issue there : https://forum.kerbalspaceprogram.com/index.php?/topic/155700-181-1101-realism-overhaul-v1311-29-jun-2021/page/79/&tab=comments#comment-3999280

After many tries to source the issue, it appears that the last version (2.0.0.0) of KSCSwitcher seems to be the source of this graphical glitch.

Attached below, you will find a screen capture of the VAB with no issue once KSCSwitcher removed. Tried also to revert to v1.8.0.0, managed to get the texture back but the Kerbal Center was not cooperative (many ground clipping).

I'm running a clean install of KSP 1.10.1 with the latest RO/RP1 release (v13.1.1) with only a selection of recommended and suggested mods, nothing else.

Best regards.
<img width="878" alt="RP1_wo_KSCSwitcher_VAB" src="https://user-images.githubusercontent.com/86570103/124352399-4cb56880-dc00-11eb-971f-6cb080c1a9a7.png">

**Comment by Tonas1997** [comment] 2021-07-17 19:08
+1. Spent an hour trying to find the culprit 😄

**Comment by Falki-git** [comment] 2021-09-06 20:23
+1

![VAB grass black](https://user-images.githubusercontent.com/72734856/132258699-f224f653-576e-4629-bf10-b67e1cb49ec2.png)

**Comment by Tonas1997** [comment] 2021-09-16 11:16
I did some investigation and tried adding the `grassColor` field to all launchsites, to no avail - I guess the problem's not caused by the "automatic grass colour" feature.

**Comment by OnlyLightMatters** [comment] 2023-11-14 11:43
Can confirm the bug can be reproduced with only KSP 1.12.5 (I had both DLCs present), last version of Module Manager and last version of KSCSwitcher with no cfg modification at all.

**Comment by siimav** [comment] 2024-07-23 11:38
Fixed in b8ee85aeb700aab6b1778cae24778b4d7db28a73

**Closed as completed by siimav** 2024-07-23 11:38 UTC
